apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cdh-http-app
  template:
    metadata:
      labels:
        app: cdh-http-app
        environment: cloud
      annotations:
        io.katacontainers.config.agent.policy: cGFja2FnZSBhZ2VudF9wb2xpY3kKCmltcG9ydCBmdXR1cmUua2V5d29yZHMuaW4KaW1wb3J0IGZ1dHVyZS5rZXl3b3Jkcy5pZgppbXBvcnQgZnV0dXJlLmtleXdvcmRzLmV2ZXJ5CgpkZWZhdWx0IEFkZEFSUE5laWdoYm9yc1JlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IEFkZFN3YXBSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBDbG9zZVN0ZGluUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgQ29weUZpbGVSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBDcmVhdGVTYW5kYm94UmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgRGVzdHJveVNhbmRib3hSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBHZXRNZXRyaWNzUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgR2V0T09NRXZlbnRSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBHdWVzdERldGFpbHNSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBMaXN0SW50ZXJmYWNlc1JlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IExpc3RSb3V0ZXNSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBNZW1Ib3RwbHVnQnlQcm9iZVJlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IE9ubGluZUNQVU1lbVJlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IFBhdXNlQ29udGFpbmVyUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgUHVsbEltYWdlUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgUmVtb3ZlQ29udGFpbmVyUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgUmVtb3ZlU3RhbGVWaXJ0aW9mc1NoYXJlTW91bnRzUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgUmVzZWVkUmFuZG9tRGV2UmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgUmVzdW1lQ29udGFpbmVyUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgU2V0R3Vlc3REYXRlVGltZVJlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IFNpZ25hbFByb2Nlc3NSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBTdGFydENvbnRhaW5lclJlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IFN0YXJ0VHJhY2luZ1JlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IFN0YXRzQ29udGFpbmVyUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgU3RvcFRyYWNpbmdSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBUdHlXaW5SZXNpemVSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBVcGRhdGVDb250YWluZXJSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBVcGRhdGVFcGhlbWVyYWxNb3VudHNSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBVcGRhdGVJbnRlcmZhY2VSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBVcGRhdGVSb3V0ZXNSZXF1ZXN0IDo9IHRydWUKZGVmYXVsdCBXYWl0UHJvY2Vzc1JlcXVlc3QgOj0gdHJ1ZQpkZWZhdWx0IFdyaXRlU3RyZWFtUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgQ3JlYXRlQ29udGFpbmVyUmVxdWVzdCA6PSB0cnVlCmRlZmF1bHQgU2V0UG9saWN5UmVxdWVzdCA6PSB0cnVlCgojIEVuYWJsZS9kaXNhYmxlIGxvZ3MKZGVmYXVsdCBSZWFkU3RyZWFtUmVxdWVzdCA6PSB0cnVlCgojIEVuYWJsZS9kaXNhYmxlIGV4ZWMKZGVmYXVsdCBFeGVjUHJvY2Vzc1JlcXVlc3QgOj0gZmFsc2UKCkV4ZWNQcm9jZXNzUmVxdWVzdCBpZiB7CiAgICBpbnB1dF9jb21tYW5kID0gY29uY2F0KCIgIiwgaW5wdXQucHJvY2Vzcy5BcmdzKQogICAgc29tZSBhbGxvd2VkX2NvbW1hbmQgaW4gcG9saWN5X2RhdGEuYWxsb3dlZF9jb21tYW5kcwogICAgaW5wdXRfY29tbWFuZCA9PSBhbGxvd2VkX2NvbW1hbmQKfQoKIyBBZGQgYWxsb3dlZCBjb21tYW5kcyBmb3IgZXhlYwpwb2xpY3lfZGF0YSA6PSB7CiAgImFsbG93ZWRfY29tbWFuZHMiOiBbCiAgICAgICAgImN1cmwgLXMgaHR0cDovLzEyNy4wLjAuMTo4MDA2L2NkaC9yZXNvdXJjZS9kZWZhdWx0L2tic3JlczEva2V5MSIKICBdCn0K
    spec:
      runtimeClassName: kata-remote
      initContainers:
        - name: initcontainer
          image: registry.redhat.io/ubi9/ubi:9.5
          env:
          - name: VPN_IP
            value: "" # TODO: insert IP
          securityContext:
            privileged: true
          command: ["sh", "-c"]
          args:
            - |
              if [ -n "$VPN_IP" ]; then
                echo "Setting vxlan remote to $VPN_IP"
                ip link set vxlan0 type vxlan remote $VPN_IP
              else
                echo "No VPN_IP defined, doing nothing"
              fi
      containers:
      - name: cdh-http-app
        image: quay.io/confidential-devhub/http-echo:latest
        resources:
          request:
            memory: "1Gi" # TODO: set this
          limits:
            memory: "1Gi" # TODO: set this
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MEMORY_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: cdh-http-app
              resource: limits.memory
        - name: ATTESTATION
          value: "1" # TODO: set this
        - name: MODEL_DECRYPTION_KEY
          value: "workload-key/key.bin" # TODO: set this
        - name: REQUEST_MEMORY_FOOTPRINT
          value: "100" # TODO: set this
        - name: MAX_MEMORY_STRESS_PERC
          value: "80" # TODO: set this
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true