---
apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
  labels:
    app: my-web-app
spec:
  selector:
    app: my-web-app
  ports:
    - port: 8888
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: my-web-app-route
  namespace: default
  labels:
    app: my-web-app
spec:
  to:
    kind: Service
    name: my-web-app-service
  port:
    targetPort: 8888
